### ISSUE TITLE
1.20.6 Can no longer get head avatars

### ISSUE THREAD

**Issue by HYDeath** [magemonkeystudio/genesis#69]
I add this on the menu will not open (below),now is there any good way to fix this?
    - customskull:e3RleHR1cmVzOntTS0lOOnt1cmw6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMThjNDQzYWRhNmUzOWZjYTgzN2EwMzgzYjBhNWUzZTU1NDc3M2I5NjYwYzQ4NzNmNTkxMDMyZGJlOWFkY2RmOCJ9fX0=

**Comment by Travja** [comment]
Are there any errors when you attempt to open the menu? 1.20.6 messed with some of that a bit, and I likely just missed something that needs to be fixed

**Comment by HYDeath** [comment]
> Are there any errors when you attempt to open the menu? 1.20.6 messed with some of that a bit, and I likely just missed something that needs to be fixed

```
    [04:41:58 ERROR]: Command exception: /genesis
org.bukkit.command.CommandException: Unhandled exception executing command 'genesis' in plugin Genesis v1.0.0-R0.4-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: The name of the profile is longer than 16 characters
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:67) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:76) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:138) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:702) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:63) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.managers.ShopCustomizer.addItem(ShopCustomizer.java:239) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.managers.ShopCustomizer.createInventory(ShopCustomizer.java:157) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.managers.ShopCustomizer.createInventory(ShopCustomizer.java:48) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.core.GenesisShop.createInventory(GenesisShop.java:166) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.core.GenesisShop.openInventory(GenesisShop.java:274) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.core.GenesisShops.openShop(GenesisShops.java:138) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.core.GenesisShops.openShop(GenesisShops.java:111) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.managers.CommandManager.playerCommandOpenShop(CommandManager.java:237) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at [G]genesis-1.0.0-R0.4-20240601.183146-1.jar/studio.magemonkey.genesis.managers.CommandManager.onCommand(CommandManager.java:204) ~[[G]genesis-1.0.0-R0.4-20240601.183146-1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 26 more
```

**Comment by Travja** [comment]
Ah. That should be easy enough to track down

**Comment by HYDeath** [comment]
> Are there any errors when you attempt to open the menu? 1.20.6 messed with some of that a bit, and I likely just missed something that needs to be fixed

According to the error it should be that the name of the head is not more than 16 characters, but at the moment this get head has to be so long that I don't know how to deal with it.

**Comment by Travja** [comment]
I need to fix our build pipelines, but the code is put together for this fix. Once that's done, there will be a new build available that I'll send you a link for to try out

**Comment by HYDeath** [comment]
> I need to fix our build pipelines, but the code is put together for this fix. Once that's done, there will be a new build available that I'll send you a link for to try out

Okay, good work. Waiting to hear about your fix.

**Comment by Travja** [comment]
Go ahead and try this out https://s01.oss.sonatype.org/content/repositories/snapshots/studio/magemonkey/genesis/1.0.0-R0.5-SNAPSHOT/genesis-1.0.0-R0.5-20240614.171040-1.jar

**Comment by HYDeath** [comment]
> Go ahead and try this out https://s01.oss.sonatype.org/content/repositories/snapshots/studio/magemonkey/genesis/1.0.0-R0.5-SNAPSHOT/genesis-1.0.0-R0.5-20240614.171040-1.jar

`[01:24:07 ERROR]: Command exception: /genesis
org.bukkit.command.CommandException: Unhandled exception executing command 'genesis' in plugin Genesis v1.0.0-R0.5-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: The name of the profile contains invalid characters: dbfd55b8-c473-41
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:68) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:76) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:138) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:702) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:63) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at org.bukkit.craftbukkit.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[paper-1.20.6.jar:1.20.6-139-79e2cb6]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.managers.ShopCustomizer.addItem(ShopCustomizer.java:239) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.managers.ShopCustomizer.createInventory(ShopCustomizer.java:157) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.managers.ShopCustomizer.createInventory(ShopCustomizer.java:48) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.core.GenesisShop.createInventory(GenesisShop.java:166) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.core.GenesisShop.openInventory(GenesisShop.java:274) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.core.GenesisShops.openShop(GenesisShops.java:138) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.core.GenesisShops.openShop(GenesisShops.java:111) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.managers.CommandManager.playerCommandOpenShop(CommandManager.java:237) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at genesis-1.0.0-R0.5-20240614.171040-1.jar/studio.magemonkey.genesis.managers.CommandManager.onCommand(CommandManager.java:204) ~[genesis-1.0.0-R0.5-20240614.171040-1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 26 more`

**Comment by Travja** [comment]
Try this one https://s01.oss.sonatype.org/content/repositories/snapshots/studio/magemonkey/genesis/1.0.0-R0.6-SNAPSHOT/genesis-1.0.0-R0.6-20240614.173125-1.jar
=

**Comment by HYDeath** [comment]
> Try this one https://s01.oss.sonatype.org/content/repositories/snapshots/studio/magemonkey/genesis/1.0.0-R0.6-SNAPSHOT/genesis-1.0.0-R0.6-20240614.173125-1.jar
This one opens the menu with the head perfectly.
![image](https://github.com/magemonkeystudio/genesis/assets/65531310/3dcf5473-c631-471e-86ad-d2b93c465ec8)
