### ISSUE TITLE
/genesis read is not working (Purpur 1.20.6)

### ISSUE THREAD

**Issue by kev2k2de** [magemonkeystudio/genesis#84]
The /genesis read command is not working at the moment. The command very useful when setting the price to an item.

Logs: https://pastes.dev/xfmMijMgAs

**Comment by Travja** [comment]
Please try this build https://s01.oss.sonatype.org/content/repositories/snapshots/studio/magemonkey/genesis/1.0.0-R0.7-SNAPSHOT/genesis-1.0.0-R0.7-20240718.060059-2.jar

**Comment by kev2k2de** [comment]
This works, thank you.

However, I noticed the following thats spamming the console every x seconds now:

```
[23:24:34 WARN]: [Genesis] Task #1655 for Genesis v1.0.0-R0.7-SNAPSHOT generated an exception
java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
        at genesis-1.0.0-R0.7-20240718.060059-2.jar/studio.magemonkey.genesis.api.GenesisAPI.isValidShop(GenesisAPI.java:60) ~[genesis-1.0.0-R0.7-20240718.060059-2.jar:?]
        at genesis-1.0.0-R0.7-20240718.060059-2.jar/studio.magemonkey.genesis.core.GenesisShops.refreshShops(GenesisShops.java:208) ~[genesis-1.0.0-R0.7-20240718.060059-2.jar:?]
        at genesis-1.0.0-R0.7-20240718.060059-2.jar/studio.magemonkey.genesis.managers.features.AutoRefreshHandler$AutoRefreshRunnable.run(AutoRefreshHandler.java:35) ~[genesis-1.0.0-R0.7-20240718.060059-2.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1734) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:503) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?
```

**Comment by Travja** [comment]
Ah... yeah. There was some changes in Spigot for 1.21 that I evidently haven't accounted for here that cause errors on older versions of Spigot/Paper. I'll get it fixed up

**Comment by Travja** [comment]
This build should resolve that error https://s01.oss.sonatype.org/content/repositories/snapshots/studio/magemonkey/genesis/1.0.0-R0.8-SNAPSHOT/genesis-1.0.0-R0.8-20240726.054005-1.jar
