### ISSUE TITLE
Latest Dev Build won't launch

### ISSUE THREAD

**Issue by DaddyRobLIVE** [magemonkeystudio/genesis#92]
[20:52:42 WARN]: [Genesis] Plugin Genesis v1.0.1-R0.3-SNAPSHOT generated an exception while executing task 2
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:220) ~[?:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.managers.item.ItemStackTranslator.checkItemStackForFeatures(ItemStackTranslator.java:196) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.core.GenesisBuy.updateShop(GenesisBuy.java:392) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.core.GenesisShop.addShopItem(GenesisShop.java:153) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.managers.BuyItemHandler.loadItem(BuyItemHandler.java:53) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.managers.config.GenesisConfigShop.loadItems(GenesisConfigShop.java:202) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.managers.config.GenesisConfigShop.setup(GenesisConfigShop.java:110) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.managers.config.GenesisConfigShop.<init>(GenesisConfigShop.java:86) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.managers.config.GenesisConfigShop.<init>(GenesisConfigShop.java:48) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.managers.config.GenesisConfigShop.<init>(GenesisConfigShop.java:41) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.core.GenesisShops.loadShop(GenesisShops.java:82) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.core.GenesisShops.loadShops(GenesisShops.java:53) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.core.GenesisShops.<init>(GenesisShops.java:31) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.managers.ClassManager.setupDependentClasses(ClassManager.java:166) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at genesis-1.0.1-R0.3-20241002.034959-1.jar/studio.magemonkey.genesis.Genesis.lambda$onEnable$0(Genesis.java:79) ~[genesis-1.0.1-R0.3-20241002.034959-1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:79) ~[leaves-1.21.1.jar:1.21.1-64-2e311f0]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaves-1.21.1.jar:1.21.1-64-2e311f0]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaves-1.21.1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by abhishekairan** [comment]
Getting the same error on reloading the plugin 
here is some of my server stats: 
- Purpur Version: 1.21.1-2321-2eaea6a (MC: 1.21.1)*
- Genesis version: genesis-1.0.1-R0.3
Issue: Genesis not working on bungeecord servers

**Comment by Travja** [comment]
This specific error should be resolved with the latest build
